### PR TITLE
Example of Palmer Penguins with Chain.jl

### PR DESCRIPTION
**Pull request by StatisticalMice**
This PR is not quite ready as I have some questions.

How should package management be done?

I would also like this plot to re-create to some extent the first plot in [palmerpenguins](https://allisonhorst.github.io/palmerpenguins/), and I currently don't know how to add the linear fit lines. In another example I made, I used AoG for that, but it's not in use here.

I also have two other versions of this plot, one with DataFramesMeta, and one with groupby(). I could add those as separate PRs, or in this one, but they need a bit of work as well.

### CODE REVIEW

**Comment by lazarusA** [comment]
- How should package management be done?
Initially, all scripts were living in the same folder because I'm using the same env for all of them (locally), without conflicts between packages and because I can generate the outputs for all using Glob and running all of them automatically. But, now I see that it might be better to put new ones in separated folders with their respective Project.toml, I will do that, for instance in your case, now this example will live in 
 _assets/scripts/penguinsDataSetWithChain/penguinsDataSetWithChain.jl and before running the script the env will be activated. I will try to do that for all future ones as well and automatically.

**Comment by lazarusA** [comment]
Ok, I added some fitted lines to the data and moved the file to a different folder as mentioned above. One problem that I encounter was that one needs to confirm the download for the dataset (the first time in the console), which prevents the script to run all the way through. Also, Makie/CairoMakie was not added initially, and since is a new environment everything needed to be added again. 
Here, the result: 

https://lazarusa.github.io/BeautifulMakie/ScattersLines/penguinsDataSetWithChain/

**Comment by StatisticalMice** [comment]
I forgot about that download prompt. There's an environment variable that can be set to bypass that. I had it in a script earlier, but I couldn't find it now. I'll keep looking.

**Comment by StatisticalMice** [comment]
@lazarusA I found it [DATADEPS_ALWAYS_ACCEPT](https://www.oxinabox.net/DataDeps.jl/dev/z10-for-end-users/#Configuration-1)

**Pull request merged**
